#!/bin/bash

LANGUAGE=python
EXTENSION=*.py
OUTPUT_FILE_NAME=$LANGUAGE.md

echo "#Python Cheat Sheet" > $OUTPUT_FILE_NAME
echo "####Written by McMaster's Competitive Programming Team" >> $OUTPUT_FILE_NAME

DIRS=`find . -type d`

for d in $DIRS
do
	if [ $d = "." ]
	then
		continue
	fi 

	echo "##$d" >> $OUTPUT_FILE_NAME
	
	FILES=`find $d -type f -name "$EXTENSION"`
	for f in $FILES 
	do
		echo "\`\`\`<$LANGUAGE>" >> $OUTPUT_FILE_NAME
		cat "$f" >> $OUTPUT_FILE_NAME
		echo "\`\`\`" >> $OUTPUT_FILE_NAME
	done	
done

